# Generated by Django 2.2.1 on 2019-05-09 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='username',
        ),
        migrations.AddField(
            model_name='users',
            name='entrytime',
            field=models.DateField(blank=True, null=True),
        ),
    ]
