# Generated by Django 2.2.1 on 2019-05-09 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='lists',
            new_name='list2',
        ),
        migrations.RenameModel(
            old_name='types',
            new_name='type2',
        ),
    ]
